import os

try:
    cxx = os.environ['CXX']
except KeyError:
    cxx = 'g++'

env = Environment(
        ENV = os.environ,
        CXX = cxx,
        CCFLAGS = '-Og -Wall -std=c++11',
        CPPPATH = ['#../../'],
        LIBPATH = ['/usr/local/lib, /usr/local/lib64'],
        LIBS    = ['stdc++', 'pthread'],
        PROGSUFFIX = '.out' )

Export('env')

SConscript('./task/SConscript', variant_dir='bin')
