import os

cxx='g++-4.8'

env = Environment(
        CXX     = cxx,
        CCFLAGS = '-Og -Wall -std=c++11',
        CPPPATH = ['#../../'],
        LIBPATH = ['/usr/local/lib, /usr/local/lib64'],
        LIBS    = ['stdc++', 'pthread'],
        PROGSUFFIX = '.out' )

Export('env')

SConscript('./task/SConscript', variant_dir='bin/task')
